### ISSUE TITLE
有一个多余的窗口看着心烦

### ISSUE THREAD

**Issue by zhangxiaocong-c17** [Longtianmu/Chat-Dragon#4]
![图片](https://user-images.githubusercontent.com/107085758/172571436-d5bd04b7-f2db-4b46-8fa9-74935b7fc3a0.png)
这个窗口关了程序就也关了 而单独占用一个窗口显得乱 能不能想办法弄没（

**Comment by Longtianmu** [comment]
测试阶段是这样的  加了个console方便看报错（
之后稳定之后会弄掉的

**Comment by Longtianmu** [comment]
现在加了Jar打包 如果你有Java Runtime的话直接用Jar就行 没有Console
